[build]
  publish = "client/build"
  command = "cd client && npm install && npm run build"

[[plugins]]
  package = "@netlify/plugin-labs"

[functions]
  directory = "server"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
