[build]
  publish = "client/build"
  command = "cd client && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

# API routes don't need redirects since we're using frontend-only approach now
