[build]
  publish = "client/build"
  command = "cd client && npm install && npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
[[functions]]
  path = "/api/*"
  function = "api"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
